default.vcl

- tried in XP, works - see `https://xp-up.ft.com/concept/search`, body: `{"term":"Enzo Ferrari"}`

Adding routing for the concept-search-api

---

default.vcl

Copies VCL from [this](https://github.com/Financial-Times/pub-varnish/pull/8/files) publishing varnish PR

Adding X-Original-Request-URL header to all requests

---

default.vcl
start.sh

See here for more details:
https://www.varnish-cache.org/lists/pipermail/varnish-announce/2017-August/000722.html

Add security exploit workaround to VCL

---

helm/delivery-varnish/app-configs/delivery-varnish_delivery.yaml
helm/delivery-varnish/app-configs/delivery-varnish_delivery_prod_eu.yaml
helm/delivery-varnish/app-configs/delivery-varnish_delivery_prod_us.yaml
helm/delivery-varnish/app-configs/delivery-varnish_delivery_staging_eu.yaml
helm/delivery-varnish/app-configs/delivery-varnish_delivery_staging_us.yaml
helm/delivery-varnish/templates/service.yaml

Add annotations for elb

---

default.vcl

Added `/content/suggest/__gtg` endpoint + renamed `draft-suggestion-api`

Suggestions umbrella changes

---

default.vcl

~~The changes are required in order to be able to purge (or banning) resources right after these are stored to UPP.
The guidelines for the changes are described [here](https://docs.google.com/a/ft.com/document/d/1OlLo4PLJYwiku9RpQT-r-J0fMKsyOJlzAZmAonJWXmQ/edit?disco=AAAAB2hABNw)
The Jira issue describing the changes can be found [here](https://jira.ft.com/browse/FDC-91).
The changes are inspired by [this](https://varnish-cache.org/docs/trunk/users-guide/purging.html#bans) documentation.~~
EDIT:
The changes are required in order to be able to purge (or banning) resources right after these are stored to UPP.
The guidelines for the changes are described in [here](https://docs.google.com/a/ft.com/document/d/1OlLo4PLJYwiku9RpQT-r-J0fMKsyOJlzAZmAonJWXmQ/edit?disco=AAAAB2hABNw)
The Jira issue …

Deploy on push/k8s/test purging cidr

---

helm/delivery-varnish/values.yaml

- see https://github.com/Financial-Times/coco-elb-dns-registrator/pull/10

Update the elb dns registrator to 5.0.0

---

helm/delivery-varnish/templates/deployment.yaml

- fix for https://github.com/Financial-Times/delivery-varnish/issues/31

Added anti-affinity config

---

default.vcl

Won't be deployed on `dev` not to interfere with the @bboykov. Will deploy on `staging` when approved.

Enable '/validate' for lists

---

default.vcl

Add live blog and internal live blog validator
Otherwise users wont be able to use `/validate` endpoint to validate such content
___

Add live blog and internal live blog validator

---

default.vcl

Adding configuration for the CCF UI service so it can be accessed without basic authentication.
JIRA ticket UPPSF-1572
Not completely sure which URL it is correct to be available without auth.
Currently it is https://upp-{env}-delivery-{region}.upp.ft.com/ccf-ui/
___

Add CCF UI

---

default.vcl

Add validators for new content types for live blogs
We need to split LiveBlogPost from LiveBlogPackage valdidation
___

Add validators for new content types for live blogs

---

default.vcl

Add configuration for audio validator
___

Add configuration for audio validator

---

default.vcl

Remove Methode preview calls
[UPPSF-1728](https://financialtimes.atlassian.net/browse/UPPSF-1728)
___

Remove Methode preview calls

---

default.vcl

Please be specific and try to describe your thought process. State the obvious, since this might be the first time the reviewer is looking at the code
Copy (if there is one) the text of the original Trello/JIRA ticket in here, with a link back to it for the curious.
___

Add VPC CIDRs for EKS VPCs in EU and US regions

---

helm/delivery-varnish/values.yaml

Please be specific and try to describe your thought process. State the obvious, since this might be the first time the reviewer is looking at the code
Copy (if there is one) the text of the original Trello/JIRA ticket in here, with a link back to it for the curious.
- [X ] Minor change (e.g. fixing a typo, adding config)
___

Adjust requests

---

default.vcl

Add `/portal` path for the C&M Web Portal
JIRA ticket UPPSF-2153
___

Add path for the C&M Web Portal

---

default.vcl

Restrict C&M Portal handled paths
___

Restrict C&M Portal handled paths

---

Dockerfile

Please be specific and try to describe your thought process. State the obvious, since this might be the first time the reviewer is looking at the code
Copy (if there is one) the text of the original Trello/JIRA ticket in here, with a link back to it for the curious.
- [ X] Minor change (e.g. fixing a typo, adding config)
___

Run autoconf

---

default.vcl

Allow /portal/specs path
JIRA ticket UPPSF-2267
___

Allow /portal/specs path

---

default.vcl

Expose the new public pages API
https://financialtimes.atlassian.net/browse/UPPSF-2396
___

Expose public-pages-api

---

helm/delivery-varnish/templates/delivery-varnish-sealed-secrets.yaml

Please be specific and try to describe your thought process. State the obvious, since this might be the first time the reviewer is looking at the code
Copy (if there is one) the text of the original Trello/JIRA ticket in here, with a link back to it for the curious.
___

Remove Opaque

---

default.vcl

Enabling validating of Live Events
[JIRA ticket](https://financialtimes.atlassian.net/browse/UPPSF-2824)
___

Adding the live event validator routes.

---

default.vcl

`cm-metadata-quality-api` will be available for other clients within the FT. As a result a more user friendly "alias" will be used, by adding an if case in this repo.
[JIRA](https://financialtimes.atlassian.net/browse/UPPSF-3558)
___

Add custom resolution for cm-metadata-quality-api

---

default.vcl

Do not require basic auth on cm-portal docs nested links.
[JIRA](https://financialtimes.atlassian.net/browse/UPPSF-4276)
___

match everything after /portal/docs

---

Dockerfile

- Change the base Dockerfile image to Ubuntu 22.04.
- Use Varnish 6.0 LTS
- Use varnish-modules 6.0 LTS branch instead of specific commit.
- Separate the Dockerfile to build and run stages
https://financialtimes.atlassian.net/browse/UPPSF-4336
The base image was changed from Alpine to Ubuntu, because the latest version of alpine (3.17) does not have build for Varnish 6. And the current vcl does not work with v7.
For varnish-modules works with 6.0-lts branch. Not sure what was the reason for using the specific commit. 
___

Change the base Dockerfile image to Ubuntu

---

Dockerfile

Use varnish 6.2.1 with latest ubuntu support version to mitigate timeout problems.
[JIRA](https://financialtimes.atlassian.net/browse/UPPSF-4336)
___

Try varnish 6.2.1 with ubuntu bionic (18.04)

---

default.vcl

Add cm-concept-lists-api routing.
[JIRA](https://financialtimes.atlassian.net/browse/UPPSF-4722)
___

add cm-concept-lists-api

---

default.vcl

Use the new endpoints in cm-search-api and fix regex
JIRA -> https://financialtimes.atlassian.net/browse/UPPSF-5008
___

Use the new endpoints in cm-search-api and fix regex

---

default.vcl

Make the regex more broad.
[UPPSF-5491](https://financialtimes.atlassian.net/browse/UPPSF-5491)
___
[UPPSF-5491]: https://financialtimes.atlassian.net/browse/UPPSF-5491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Expand regex for content/query

---

default.vcl

Do not route concept-search-api POST endpoint to api-policy-component
JIRA Ticket [UPPSF-5291](https://financialtimes.atlassian.net/browse/UPPSF-5291)
___
[UPPSF-5291]: https://financialtimes.atlassian.net/browse/UPPSF-5291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Do not route concept-search-api POST endpoint to api-policy-component

---

default.vcl

Expose one of the endpoints of the relations API.
Please check [the PR in relations API](https://github.com/Financial-Times/relations-api/pull/34). 
https://financialtimes.atlassian.net/browse/UPPSF-5542
_This API doesn't need to go trough api-policy-component that's why it is configured in this varnish._  
___

Expose an endpoint of the relations API

---

default.vcl

Route Public Concepts API requests directly to the app
[JIRA](https://financialtimes.atlassian.net/browse/UPPSF-5579)
___

route public-concepts requests directly

---

default.vcl

This change adds necessary routing to enable the new Ontotext Suggestions with Details endpoint.
Ticket: https://financialtimes.atlassian.net/browse/UPPSF-6075
___

[UPPSF-6075] Expose Ontotext Suggestions with Details endpoint

---

default.vcl

This PR This PR exposes the newly created `cm-content-tree-api` via endpoint /content-tree/{uuid}.
JIRA --> https://financialtimes.atlassian.net/browse/UPPSF-6158
- [x ] Feature
___

expose /content-tree endpoint of cm-content-tree-api
